$$
Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \dots + \beta_mX_m + \varepsilon
$$

$$
\hat{Y} = \beta_0 + \beta_1X_1 + \beta_2X_2 + \dots + \beta_mX_m
$$

$$
Y = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix}
$$

$$
X = \begin{bmatrix} 1 & x_{11}  & x_{12} & \cdots x_{1m} \\ 1 &  x_{21}  & x_{22} & \cdots x_{2m} \\ \vdots \\ 1 & x_{n1} & x_{n2} & \cdots x_{nm} \end{bmatrix}
$$

$$
\beta = \begin{bmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \\ \vdots \\ \beta_m \end{bmatrix}
$$

$$
X \beta = \begin{bmatrix} 1 & x_{11}  & x_{12} & \cdots x_{1m} \\ 1 &  x_{21}  & x_{22} & \cdots x_{2m} \\ \vdots \\ 1 & x_{n1} & x_{n2} & \cdots x_{nm} \end{bmatrix} \begin{bmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \\ \vdots \\ \beta_m \end{bmatrix} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix}
$$

$$
\hat{Y} = X \beta
$$

$$
\hat{Y} = \beta_0 + \beta_1X_1 + \beta_2X_2 + \dots + \beta_mX_m
$$

$$
\varepsilon = \begin{bmatrix} \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_n \end{bmatrix}
$$

$$
Y - \hat{Y}
$$

$$
\text{Loss} = \frac{1}{N} \sum_{i=0}^n (\varepsilon_i)^2 \to \text{minimum}
$$

$$
\begin{bmatrix} \varepsilon_1 \varepsilon_2 \cdots \varepsilon_n \end{bmatrix} \begin{bmatrix} \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_n \end{bmatrix}
$$

$$
\text{MSE}(\beta) = \frac{1}{N} \varepsilon^T \varepsilon
$$

$$
\text{MSE}(\beta) = \frac{1}{N} (Y - X \beta)^T (Y - X \beta) = (Y^T - \beta^T X^T) (Y - X \beta)
$$

$$
(Y^TY - Y^TX\beta - \beta^TX^TY + \beta^TX^TX\beta)
$$

$Y^TX\beta = (\beta^TX^TY)^T$

$$
\text{MSE}(\beta) = \frac{1}{N}(Y^TY - 2\beta^TX^TY + \beta^TX^TX\beta)
$$

$$
\frac{\partial \text{MSE}(\beta)}{\partial \beta} = \nabla \text{MSE}(\beta)
$$

$$
\nabla \text{MSE}(\beta) = \nabla Y^TY - 2 \nabla \beta^TX^TY + \nabla \beta^TX^TX\beta
$$

$$
\nabla \text{MSE}(\beta) = X^TX\beta - X^Ty = 0
$$

$$
X^TX\beta - X^Ty = 0
$$

$$
X^TX\beta = X^Ty
$$

$$
\beta = (X^TX)^{-1}X^Ty
$$

## Coding

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/advertising.csv')
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [17]:
X_org = df[['TV', 'Radio', 'Newspaper']].values
y = df['Sales'].values
N = X_org.shape[0]
X = np.c_[np.ones(N), X_org]

In [18]:
np.linalg.inv(X.T @ X) @ X.T @ y # type: ignore

array([4.62512408e+00, 5.44457803e-02, 1.07001228e-01, 3.35657922e-04])

In [19]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y # type: ignore

In [20]:
beta

array([4.62512408e+00, 5.44457803e-02, 1.07001228e-01, 3.35657922e-04])

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_org, y) # type: ignore

LinearRegression()

In [22]:
lin_reg.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [23]:
lin_reg.intercept_

np.float64(4.625124078808653)

In [26]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [27]:
lin_reg.score(X_org, y)

0.9025912899684558

In [30]:
import statsmodels.api as sm

model = sm.OLS(y, X).fit() # Ordinary Least Squares

In [31]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Tue, 10 Jun 2025   Prob (F-statistic):           8.13e-99
Time:                        21:41:54   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.6251      0.308     15.041      0.000       4.019       5.232
x1             0.0544      0.001     39.592      0.000       0.052       0.057
x2             0.1070      0.008     12.604      0.000       0.090       0.124
x3             0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""