In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [35]:
df = pd.read_csv('data/advertising.csv')
X = df.drop(columns=['Sales']).values
y = df['Sales'].values

In [30]:
std_scl = StandardScaler()
make_poly = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)
lin_reg = LinearRegression()

In [31]:
X[:5]

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4]])

In [32]:
X = std_scl.fit_transform(X)
X[:5]

array([[ 0.96985227,  0.98152247,  1.77894547],
       [-1.19737623,  1.08280781,  0.66957876],
       [-1.51615499,  1.52846331,  1.78354865],
       [ 0.05204968,  1.21785493,  1.28640506],
       [ 0.3941822 , -0.84161366,  1.28180188]])

In [33]:
X = make_poly.fit_transform(X)
X[:5]

array([[ 0.96985227,  0.98152247,  1.77894547,  0.95193179,  1.72531429,
         1.74607495],
       [-1.19737623,  1.08280781,  0.66957876, -1.29652833, -0.80173769,
         0.72502511],
       [-1.51615499,  1.52846331,  1.78354865, -2.31738727, -2.70413618,
         2.72608867],
       [ 0.05204968,  1.21785493,  1.28640506,  0.06338896,  0.06695697,
         1.56665475],
       [ 0.3941822 , -0.84161366,  1.28180188, -0.33174912,  0.50526348,
        -1.07878197]])

In [34]:
X.shape

(200, 6)

In [25]:
lin_reg.fit(X, y)

LinearRegression()

In [26]:
y_pred = lin_reg.predict(X)

In [27]:
lin_reg.score(X, y)

0.9355054136573707

# Data Splitting

## Train Split / Test Split

Generalisation Loss

In [36]:
df = pd.read_csv('data/advertising.csv')
X = df.drop(columns=['Sales']).values
y = df['Sales'].values

In [37]:
X.shape

(200, 3)

In [38]:
train_size = int(0.7 * X.shape[0])
train_size

140

In [40]:
X_train = X[:train_size]
X_test = X[train_size:]

y_train, y_test = y[:train_size], y[train_size:]

X_train.shape, X_test.shape

((140, 3), (60, 3))

In [41]:
y_train.shape, y_test.shape

((140,), (60,))

In [53]:
ix = np.random.permutation(X.shape[0])

In [63]:
X[ix] # shuffled X
y[ix] # shuffled y

train_size = int(0.7 * X.shape[0])

X_train = X[ix][:train_size]
X_test = X[ix][train_size:]

y_train, y_test = y[ix][:train_size], y[ix][train_size:]

X_train.shape, X_test.shape

((140, 3), (60, 3))

In [64]:
from sklearn.model_selection import train_test_split

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [96]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((140, 3), (60, 3), (140,), (60,))

In [97]:
std_scl = StandardScaler()
make_poly = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)
lin_reg = LinearRegression()

In [98]:
X_train = std_scl.fit_transform(X_train)
X_train = make_poly.fit_transform(X_train)

In [99]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [100]:
lin_reg.score(X_train, y_train)

0.9020813344967064

In [101]:
from sklearn.metrics import root_mean_squared_error

In [102]:
y_pred = lin_reg.predict(X_train)

In [103]:
root_mean_squared_error(y_train, y_pred)

1.6041702621097962

In [107]:
X_test = std_scl.transform(X_test)
X_test = make_poly.transform(X_test)

In [108]:
lin_reg.score(X_test, y_test)

0.9263697359671811

In [109]:
lin_reg

LinearRegression()

### How can we use this model?

In [110]:
lin_reg.coef_

array([ 4.48646421,  1.52054778,  0.12062109,  0.51359714, -0.11101447,
        0.11551558])

In [111]:
lin_reg.intercept_

np.float64(15.71249489788946)

In [112]:
std_scl.scale_

array([83.59965712, 14.58321503, 20.62458473])

In [113]:
std_scl.mean_

array([156.38928571,  23.525     ,  30.44785714])

In [116]:
std_scl.transform(np.array([[230.1, 37.8, 69.2]]))

array([[0.88171072, 0.97886508, 1.87892961]])

In [117]:
(np.array([[230.1, 37.8, 69.2]]) - std_scl.mean_) / std_scl.scale_

array([[0.88171072, 0.97886508, 1.87892961]])

In [118]:
X_train.shape

(140, 6)

In [119]:
make_poly

PolynomialFeatures(include_bias=False, interaction_only=True)

In [120]:
lin_reg

LinearRegression()

In [121]:
import joblib

In [122]:
joblib.dump(std_scl, 'standard_scaler.joblib')
joblib.dump(make_poly, 'make_poly.joblib')
joblib.dump(lin_reg, 'linear_regression.joblib')

['linear_regression.joblib']