In [1]:
# Building Regression Model using Keras Sequential API
from tensorflow.keras.datasets import california_housing

In [2]:
housing = california_housing.load_data()

743530/743530 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
(X_train, y_train), (X_test, y_test) = housing

In [7]:
X_train.shape

(16512, 8)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Normalization, InputLayer

In [53]:
norm_layer = Normalization(name='norm_layer')

model = Sequential([
    InputLayer(shape=[8], name='input_layer'),
    norm_layer,
    Dense(100, activation='relu', name='hidden1'),
    Dense(100, activation='relu', name='hidden2'),
    Dense(100, activation='relu', name='hidden3'),
    Dense(1, name='output') # output layer
])

In [54]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ norm_layer (Normalization)      │ (None, 8)              │            17 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden1 (Dense)                 │ (None, 100)            │           900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden2 (Dense)                 │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden3 (Dense)                 │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,218 (82.89 KB)

 Trainable params: 21,201 (82.82 KB)

 Non-trainable params: 17 (72.00 B)

In [55]:
norm_layer.get_weights()

[array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 np.int64(0)]

In [56]:
norm_layer.adapt(X_train)

In [57]:
norm_layer.get_weights()

[array([-119.56227  ,   35.625397 ,   28.65413  , 2644.7268   ,
         539.5743   , 1433.2728   ,  501.45834  ,    3.8701892],
       dtype=float32),
 array([4.0044060e+00, 4.5356297e+00, 1.5868558e+02, 4.8844355e+06,
        1.8159067e+05, 1.3370920e+06, 1.5020797e+05, 3.6010580e+00],
       dtype=float32),
 np.int64(0)]

In [58]:
from tensorflow.keras.optimizers import SGD, Adam

In [59]:
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mse', metrics=['RootMeanSquaredError'])

In [60]:
history = model.fit(X_train, y_train, epochs=50, validation_split=0.2)

Epoch 1/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - RootMeanSquaredError: 226324.5781 - loss: 51374301184.0000 - val_RootMeanSquaredError: 111884.1484 - val_loss: 12518062080.0000
Epoch 2/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - RootMeanSquaredError: 104566.7891 - loss: 10951322624.0000 - val_RootMeanSquaredError: 87821.6641 - val_loss: 7712645120.0000
Epoch 3/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 86151.8672 - loss: 7429241344.0000 - val_RootMeanSquaredError: 76948.4297 - val_loss: 5921061376.0000
Epoch 4/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - RootMeanSquaredError: 75893.9531 - loss: 5760472576.0000 - val_RootMeanSquaredError: 71009.4688 - val_loss: 5042344448.0000
Epoch 5/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - RootMeanSquaredError: 71791.2266 - loss: 5159860736.0000 - val_RootMeanSquaredError: 68116.7500 - val_loss: 4639891456.0000
Epoch 6/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 68744.2578 - loss: 472960102

In [32]:
y_train[:5]

array([252300., 146900., 290900., 141300., 500001.], dtype=float32)

In [61]:
y_pred = model.predict(X_train)

516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


In [35]:
model.evaluate(X_train, y_train)

516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - RootMeanSquaredError: 65245.1172 - loss: 4258212096.0000


[4210350336.0, 64887.2109375]

In [36]:
from tensorflow.keras.metrics import R2Score

In [62]:
scorer = R2Score()

In [63]:
scorer.update_state(y_train, y_pred)

In [64]:
scorer.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.6943517327308655>

# Functional API

In [74]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Normalization, Input, Concatenate

In [75]:
normalization_layer = Normalization()
hidden_layer1 = Dense(30, activation='relu')
hidden_layer2 = Dense(30, activation='relu')
concat_layer = Concatenate()
output_layer = Dense(1)

input_ = Input(shape=[8])

normalized = normalization_layer(input_)
hidden1 = hidden_layer1(normalized)
hidden2 = hidden_layer2(hidden1)

concatenated = concat_layer([input_, hidden2])

output = output_layer(concatenated)

model = Model(inputs=[input_], outputs=[output])

In [76]:
model.summary()

Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_7       │ (None, 8)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ normalization_9     │ (None, 8)         │         17 │ input_layer_7[0]… │
│ (Normalization)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_26 (Dense)    │ (None, 30)        │        270 │ normalization_9[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_27 (Dense)    │ (None, 30)        │        930 │ dense_26[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 38)        │          0 │ input_layer_7[0]… │
│ (Concatenate)       │                   │            │ dense_27[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_28 (Dense)    │ (None, 1)         │         39 │ concatenate[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,256 (4.91 KB)

 Trainable params: 1,239 (4.84 KB)

 Non-trainable params: 17 (72.00 B)

In [77]:
model.save('deep_and_wide_model.keras')

In [87]:
input_layer_deep = Input([4])
input_layer_wide = Input([4])

normalization_layer_deep = Normalization(name='norm_deep')
normalization_layer_wide = Normalization(name='norm_wide')

hidden_layer1 = Dense(30, activation='relu')
hidden_layer2 = Dense(30, activation='relu')
concat_layer = Concatenate()
output_layer = Dense(1)

# ---------------------

normalized_deep = normalization_layer_deep(input_layer_deep)
normalized_wide = normalization_layer_wide(input_layer_wide)

hidden1 = hidden_layer1(normalized_deep)
hidden2 = hidden_layer2(hidden1)

concatenated = concat_layer([hidden2, normalized_wide])

output = output_layer(concatenated)

model = Model(inputs=[normalized_wide, input_layer_deep], outputs=[output, hidden2])

In [ ]:
normalization_layer_deep.adapt()
normalization_layer_wide.adapt()

In [88]:
model.save('multiple_output_model.keras')

# Subclass API

In [89]:
from tensorflow.keras.models import Model

In [116]:
class MyModel(Model):
  def __init__(self, units=30, out=1, activation='relu', **kwargs):
    super().__init__(**kwargs)
    # self.input_layer = InputLayer(shape=shape)
    self.norm_layer = Normalization()
    self.hidden1 = Dense(units, activation=activation)
    self.hidden2 = Dense(units, activation=activation)
    self.out = Dense(1)

  def call(self, X):
    # X = self.input_layer(X)
    X = self.norm_layer(X)
    # print('here')
    X = self.hidden1(X)
    X = self.hidden2(X)
    X = self.out(X)
    return X

my_model = MyModel(units=50)
my_model.norm_layer.adapt(X_train)

In [117]:
optimizer = Adam(learning_rate=0.001)
my_model.compile(optimizer=optimizer, loss='mse', metrics=['RootMeanSquaredError'])
history = my_model.fit(X_train, y_train, epochs=50, validation_split=0.2)

Epoch 1/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - RootMeanSquaredError: 237005.1250 - loss: 56173940736.0000 - val_RootMeanSquaredError: 236999.6250 - val_loss: 56168820736.0000
Epoch 2/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - RootMeanSquaredError: 233607.8906 - loss: 54578540544.0000 - val_RootMeanSquaredError: 228914.3594 - val_loss: 52401786880.0000
Epoch 3/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 223582.4688 - loss: 50007498752.0000 - val_RootMeanSquaredError: 210197.5781 - val_loss: 44183023616.0000
Epoch 4/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 202325.6719 - loss: 40950759424.0000 - val_RootMeanSquaredError: 182672.5469 - val_loss: 33369262080.0000
Epoch 5/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 173863.4375 - loss: 30247081984.0000 - val_RootMeanSquaredError: 152514.7812 - val_loss: 23260760064.0000
Epoch 6/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 145468.8438 - 

In [118]:
my_model.save('custom.keras')

In [119]:
my_model.summary()

Model: "my_model_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ normalization_23                │ (16512, 8)             │            17 │
│ (Normalization)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_70 (Dense)                │ (None, 50)             │           450 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_71 (Dense)                │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_72 (Dense)                │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,172 (35.84 KB)

 Trainable params: 3,051 (11.92 KB)

 Non-trainable params: 17 (72.00 B)

 Optimizer params: 6,104 (23.85 KB)